name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: TuneAPI Tests
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests
        run: swift test --package-path Packages/TuneAPI --filter TuneAPITests

      - name: Run integration tests
        run: swift test --package-path Packages/TuneAPI --filter TuneAPIIntegrationTests

        # TODO: Fix it so we can have all tests running
  # app-tests:
  #   name: App Tests
  #   runs-on: macos-26

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Run app tests
  #       run: |
  #         xcodebuild test \
  #           -project TuneFlow.xcodeproj \
  #           -scheme TuneFlow \
  #           -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.1' \
  #           -resultBundlePath TestResults \
  #           CODE_SIGNING_ALLOWED=NO
